name: dating_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  rename: ^3.0.1
  google_sign_in: ^6.1.5
  animated_bottom_navigation_bar: ^1.3.0
  flutter_animate: ^4.2.0+1
  file_picker: ^5.3.1
  firebase_storage: ^11.4.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  flutter_card_swiper: ^6.0.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/ 
  uses-material-design: true

